# Generated by Django 6.0.4 on 2026-05-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='https://media.istockphoto.com/id/2173059563/vector/coming-soon-image-on-white-background-no-photo-available.jpg?s=612x612&w=0&k=20&c=v0a_B58wPFNDPULSiw_BmPyhSNCyrP_d17i2BPPyDTk=', null=True, upload_to='tasks_asset'),
        ),
    ]
